CREATE TABLE trade
(
    id            BIGSERIAL PRIMARY KEY,
    trade_id      VARCHAR(255),
    instrument    VARCHAR(255),
    price         DOUBLE PRECISION, --WE KNOW ITS NOT OK TO USE FLOATS FOR MONEY BUT THIS IS NOT A REAL PROJECT!!!
    quantity      INTEGER,
    source_system VARCHAR(255),
    trade_date    DATE
);

CREATE TABLE instrument
(
    id     BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(50) NOT NULL,
    name   VARCHAR(100),
    isin   VARCHAR(20)
);

CREATE TABLE reconciliation_run
(
    id              BIGSERIAL PRIMARY KEY,
    run_date        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status          VARCHAR(20),
    matched_count   INTEGER,
    unmatched_count INTEGER
);


CREATE TABLE reconciliation_difference
(
    id                    BIGSERIAL PRIMARY KEY,
    trade_id              VARCHAR(255) NOT NULL,
    field_name            VARCHAR(100),
    value_system_a        VARCHAR(255),
    value_system_b        VARCHAR(255),
    reconciliation_run_id BIGINT REFERENCES reconciliation_run (id) ON DELETE CASCADE
);

CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(255),
    password                VARCHAR(255),
    role                    SMALLINT,
    account_non_expired     BOOLEAN,
    account_non_locked      BOOLEAN,
    credentials_non_expired BOOLEAN,
    enabled                 BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (id)
);